spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: guanlei
    url: jdbc:mysql://127.0.0.1:3306/fms?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      #启动程序时，在连接池中初始化多少个连接
      initialSize: 5
      #最小连接池数量
      minIdle: 5
      ##连接池中最多支持多少个活动会话
      maxActive: 20
      #获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      #有两个含义：
      #1) Destroy线程会检测连接的间隔时间
      #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      timeBetweenEvictionRunsMillis: 60000
      # Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于，minEvictableIdleTimeMillis，则关闭当前连接
      minEvictableIdleTimeMillis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句。
      validationQuery: SELECT 1 FROM DUAL
      #建议配置为true，不影响性能，并且保证安全性。
      #申请连接的时候检测，如果空闲时间大于
      #timeBetweenEvictionRunsMillis，
      #执行validationQuery检测连接是否有效。
      testWhileIde: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会影响性能
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会影响性能
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache mql5.5以上建议开启
      #poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j2
      #maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gl.springcloud.entity
