server:
  port: 8806
  servlet:
    context-path: /bootDemo
  tomcat:
    uri-encoding: UTF-8

#在SpringBoot中多环境配置文件名需要满足application-{profile}.yml的格式。至于哪个具体的配置文件会被加载，需要在application.yml文件中通过spring.profiles.active属性来设置，其值对应{profile}值。
spring:
  profiles:
    active: dev

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 2000 #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 5 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5   #连接池中的最大空闲连接
        min-idle: 0   #连接池中的最小空闲连接

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${db.userName}
    password: ${db.password}
    url: jdbc:mysql://${db.host}/${db.database}?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    #以下为Druid连接池配置
    initialSize: 1
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    queryTimeout: 100
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gl.springcloud.entity

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true