server:
  port: 8806
  servlet:
    context-path: /springboot
  tomcat:
    uri-encoding: UTF-8

#在SpringBoot中多环境配置文件名需要满足application-{profile}.yml的格式。至于哪个具体的配置文件会被加载，需要在application.yml文件中通过spring.profiles.active属性来设置，其值对应{profile}值。
spring:
  profiles:
    active: dev

  redis:
    host: ${redis.host}
    port: ${redis.port}
  # cluster:
  #    max-redirects: 3  #获取失败后最大重定向次数
  #    nodes:
  #     - 127.0.0.1:7001
  #     - 127.0.0.1:7002
  #     - 127.0.0.1:7003
    password: ${redis.password}
    timeout: 2000 #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 5 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5   #连接池中的最大空闲连接
        min-idle: 0   #连接池中的最小空闲连接

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${db.userName}
    password: ${db.password}
    url: jdbc:mysql://${db.host}/${db.database}?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    #以下为Druid连接池配置
    initialSize: 1
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    queryTimeout: 100
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false

  #设置返回的bean对象的时间属性格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    defaultPropertyInclusion: non_null #不为空的属性才会序列化
    serialization:
      write-dates-as-timestamps: false #返回的java.util.date转换成timestamp
    serialization-inclusion: NON_NULL
    time-zone: Asia/Shanghai  #设置全局时区

#整合mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gl.springcloud.entity

#整合mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出SQL语句
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: N
      # 删除后
      logic-delete-value: Y

#整合pagehelper
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

###################################以下为系统自定义参数################################
cleanTask:
  fixedDelay: 1000
  cron: 0/5 * * * * ?